/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Verifica todos los servicios en paralelo; responde 200 siempre.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sources */
        get: operations["list_sources_v1_sources_get"];
        put?: never;
        /** Create Source */
        post: operations["create_source_v1_sources_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sources/{source_uuid}/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sync Source */
        post: operations["sync_source_v1_sources__source_uuid__sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Note */
        post: operations["create_note_v1_notes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Documents */
        get: operations["list_documents_v1_documents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/documents/{doc_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Document */
        get: operations["get_document_v1_documents__doc_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/documents/{doc_id}/chunks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Chunks */
        get: operations["list_chunks_v1_documents__doc_id__chunks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Search */
        post: operations["search_v1_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Query */
        post: operations["query_v1_query_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/graph/nodes/{node_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Node */
        get: operations["get_node_v1_graph_nodes__node_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Node */
        patch: operations["patch_node_v1_graph_nodes__node_id__patch"];
        trace?: never;
    };
    "/v1/graph/path": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Path */
        get: operations["get_path_v1_graph_path_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/graph/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Query */
        post: operations["query_v1_graph_query_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/graph/relations/{relation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Relation */
        delete: operations["delete_relation_v1_graph_relations__relation_id__delete"];
        options?: never;
        head?: never;
        /** Patch Relation */
        patch: operations["patch_relation_v1_graph_relations__relation_id__patch"];
        trace?: never;
    };
    "/v1/memory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Memories */
        get: operations["list_memories_v1_memory_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/memory/{memory_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Archive Memory */
        delete: operations["archive_memory_v1_memory__memory_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Plans */
        get: operations["list_plans_v1_plans_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/plans/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Plan Metrics */
        get: operations["get_plan_metrics_v1_plans_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/plans/{plan_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Plan */
        get: operations["get_plan_v1_plans__plan_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Conversations */
        get: operations["list_conversations_v1_conversations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/conversations/{conversation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Conversation */
        get: operations["get_conversation_v1_conversations__conversation_id__get"];
        put?: never;
        post?: never;
        /** Archive Conversation */
        delete: operations["archive_conversation_v1_conversations__conversation_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Recommendations */
        get: operations["list_recommendations_v1_recommendations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/recommendations/{recommendation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Recommendation
         * @description Aceptar/descartar (doc 11 §8): nunca escribe al grafo ni al vault —
         *     solo cambia el estado de la `Recommendation`. Descartar además evita que
         *     la misma laguna/contradicción reaparezca en la próxima pasada del
         *     Recomendador (`has_active_recommendation`, `postgres.py`).
         */
        patch: operations["update_recommendation_v1_recommendations__recommendation_id__patch"];
        trace?: never;
    };
    "/v1/memory/proposals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Proposals */
        get: operations["list_proposals_v1_memory_proposals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/memory/proposals/{proposal_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Proposal
         * @description Aprobar escribe la memoria de verdad (vía `memory.store` con
         *     `confirm=True`, `memory_proposal_service.resolve_proposal`); rechazar solo
         *     cierra la propuesta.
         */
        patch: operations["update_proposal_v1_memory_proposals__proposal_id__patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AgentDistribution */
        AgentDistribution: {
            /** Agent */
            agent: string;
            /** Count */
            count: number;
        };
        /**
         * AgentLatency
         * @description Promedio de `cost.ms` por agente sobre los pasos con costo registrado
         *     (doc 06 §2 addendum: `agent_distribution` ya contaba pasos por agente,
         *     pero no si `research`/`memory` es sistemáticamente el cuello de botella —
         *     `count` acá es la cantidad de pasos con `cost.ms` presente, no el total de
         *     pasos de ese agente).
         */
        AgentLatency: {
            /** Agent */
            agent: string;
            /** Avg Ms */
            avg_ms: number;
            /** Count */
            count: number;
        };
        /** ChunkOut */
        ChunkOut: {
            /**
             * Chunk Id
             * Format: uuid
             */
            chunk_id: string;
            /**
             * Doc Id
             * Format: uuid
             */
            doc_id: string;
            /** Text */
            text: string;
            /** Position */
            position: number;
            /** Start Offset */
            start_offset: number | null;
            /** End Offset */
            end_offset: number | null;
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
            /** Has Embedding */
            has_embedding: boolean;
        };
        /** ChunkPage */
        ChunkPage: {
            /** Items */
            items: components["schemas"]["ChunkOut"][];
            /** Next Cursor */
            next_cursor: number | null;
        };
        /** ConversationDetail */
        ConversationDetail: {
            conversation: components["schemas"]["ConversationOut"];
            /** Messages */
            messages: components["schemas"]["MessageOut"][];
        };
        /** ConversationOut */
        ConversationOut: {
            /**
             * Conversation Id
             * Format: uuid
             */
            conversation_id: string;
            /** Title */
            title: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ConversationPage */
        ConversationPage: {
            /** Items */
            items: components["schemas"]["ConversationOut"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /**
         * Cost
         * @description Coste observado de una ejecución (para trazas y métricas, doc 09 §6).
         */
        Cost: {
            /**
             * Tokens
             * @default 0
             */
            tokens: number;
            /**
             * Ms
             * @default 0
             */
            ms: number;
        };
        /** DegradationBreakdown */
        DegradationBreakdown: {
            /** Reason */
            reason: string | null;
            /** Count */
            count: number;
        };
        /** DocumentDetail */
        DocumentDetail: {
            /**
             * Doc Id
             * Format: uuid
             */
            doc_id: string;
            /** Source Uuid */
            source_uuid: string | null;
            /** Connector */
            connector: string;
            /** Source Id */
            source_id: string;
            /** Title */
            title: string | null;
            /** Summary */
            summary: string | null;
            /** Author */
            author: string | null;
            /** Language */
            language: string | null;
            /** Keywords */
            keywords: string[];
            /** Links */
            links: string[];
            /** Confidence */
            confidence: number;
            /** Content Hash */
            content_hash: string | null;
            /** Created At */
            created_at: string | null;
            /** Modified At */
            modified_at: string | null;
            /**
             * Fetched At
             * Format: date-time
             */
            fetched_at: string;
            /** Source Metadata */
            source_metadata: {
                [key: string]: unknown;
            };
        };
        /** DocumentPage */
        DocumentPage: {
            /** Items */
            items: components["schemas"]["DocumentSummary"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** DocumentSummary */
        DocumentSummary: {
            /**
             * Doc Id
             * Format: uuid
             */
            doc_id: string;
            /** Source Uuid */
            source_uuid: string | null;
            /** Connector */
            connector: string;
            /** Source Id */
            source_id: string;
            /** Title */
            title: string | null;
            /** Summary */
            summary: string | null;
            /** Author */
            author: string | null;
            /** Language */
            language: string | null;
            /** Keywords */
            keywords: string[];
            /** Links */
            links: string[];
            /** Confidence */
            confidence: number;
            /** Content Hash */
            content_hash: string | null;
            /** Created At */
            created_at: string | null;
            /** Modified At */
            modified_at: string | null;
            /**
             * Fetched At
             * Format: date-time
             */
            fetched_at: string;
        };
        /**
         * EvidenceRef
         * @description Referencia citable. La evidencia mínima es {doc_id, chunk_id, quote};
         *     node_id/memory_id se rellenan en fases posteriores (grafo, memoria).
         */
        EvidenceRef: {
            /** Doc Id */
            doc_id?: string | null;
            /** Chunk Id */
            chunk_id?: string | null;
            /** Node Id */
            node_id?: string | null;
            /** Memory Id */
            memory_id?: string | null;
            /** Quote */
            quote?: string | null;
            /** Title */
            title?: string | null;
            /** Source Id */
            source_id?: string | null;
            /** Connector */
            connector?: string | null;
            /** Score */
            score?: number | null;
            /** Doc Type */
            doc_type?: string | null;
        };
        /** GraphNeighbor */
        GraphNeighbor: {
            relation: components["schemas"]["GraphRelation"];
            node: components["schemas"]["GraphNode"];
            /**
             * Direction
             * @enum {string}
             */
            direction: "outgoing" | "incoming";
        };
        /** GraphNode */
        GraphNode: {
            /** Id */
            id: string;
            /**
             * Node Type
             * @enum {string}
             */
            node_type: "Person" | "Project" | "Technology" | "Concept" | "Document" | "Task" | "Organization" | "Event" | "Skill";
            /** Canonical Name */
            canonical_name: string;
            /** Name */
            name: string;
            /** Aliases */
            aliases?: string[];
            /** Confidence */
            confidence: number;
            /** Sources */
            sources?: string[];
            /** Extracted By */
            extracted_by: string;
            /**
             * Locked
             * @default false
             */
            locked: boolean;
            /** Created At */
            created_at?: string | null;
            /** Updated At */
            updated_at?: string | null;
            /**
             * Prune Candidate
             * @description Doc 04 §5: confidence bajo el umbral tras perder una fuente.
             */
            readonly prune_candidate: boolean;
        };
        /** GraphPathOut */
        GraphPathOut: {
            /** Nodes */
            nodes: components["schemas"]["GraphNode"][];
            /** Relations */
            relations: components["schemas"]["GraphRelation"][];
        };
        /** GraphQueryRequest */
        GraphQueryRequest: {
            /**
             * Template
             * @enum {string}
             */
            template: "nodes_by_type" | "neighbors_by_type" | "most_connected" | "subgraph";
            /** Node Type */
            node_type?: string | null;
            /** Node Id */
            node_id?: string | null;
            /** Cursor */
            cursor?: string | null;
            /**
             * Limit
             * @default 20
             */
            limit: number;
        };
        /** GraphQueryResponse */
        GraphQueryResponse: {
            /**
             * Template
             * @enum {string}
             */
            template: "nodes_by_type" | "neighbors_by_type" | "most_connected" | "subgraph";
            /** Nodes */
            nodes?: components["schemas"]["GraphNode"][] | null;
            /** Neighbors */
            neighbors?: components["schemas"]["GraphNeighbor"][] | null;
            /** Relations */
            relations?: components["schemas"]["GraphRelation"][] | null;
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** GraphRelation */
        GraphRelation: {
            /** Id */
            id: string;
            /**
             * Relation Type
             * @enum {string}
             */
            relation_type: "USES" | "RELATED_TO" | "AUTHORED_BY" | "PART_OF" | "DEPENDS_ON" | "PREREQUISITE_OF" | "MENTIONS" | "KNOWS" | "CONTRADICTS" | "SUPERSEDES";
            /** Source Id */
            source_id: string;
            /** Target Id */
            target_id: string;
            /** Confidence */
            confidence: number;
            /** Sources */
            sources?: string[];
            /** Extracted By */
            extracted_by: string;
            /** Extracted At */
            extracted_at?: string | null;
            /**
             * Rejected
             * @default false
             */
            rejected: boolean;
            /**
             * Prune Candidate
             * @description Doc 04 §5: confidence bajo el umbral tras perder una fuente.
             */
            readonly prune_candidate: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /** Services */
            services: {
                [key: string]: components["schemas"]["ServiceStatus"];
            };
        };
        /** Insight */
        Insight: {
            /**
             * Severity
             * @enum {string}
             */
            severity: "info" | "warning" | "critical";
            /**
             * Metric
             * @enum {string}
             */
            metric: "latency" | "degradation" | "agent_distribution" | "tokens";
            /** Message */
            message: string;
            /** Delta Pct */
            delta_pct?: number | null;
        };
        /** LatencyBucket */
        LatencyBucket: {
            /**
             * Bucket
             * Format: date-time
             */
            bucket: string;
            /** Avg Ms */
            avg_ms: number;
            /** Count */
            count: number;
        };
        /** MemoryOut */
        MemoryOut: {
            /**
             * Memory Id
             * Format: uuid
             */
            memory_id: string;
            /**
             * Type
             * @enum {string}
             */
            type: "episodic" | "semantic" | "procedural" | "temporal" | "preference";
            /** Content */
            content: string;
            /** Entities */
            entities: string[];
            /** Sources */
            sources: components["schemas"]["SourceRef"][];
            /** Confidence */
            confidence: number;
            /** Salience */
            salience: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Last Accessed At
             * Format: date-time
             */
            last_accessed_at: string;
            /** Archived At */
            archived_at: string | null;
            /** Superseded By */
            superseded_by: string | null;
            /**
             * Prune Candidate
             * @description Doc 04 §5: confidence bajo el umbral tras perder una fuente.
             */
            readonly prune_candidate: boolean;
        };
        /** MemoryPage */
        MemoryPage: {
            /** Items */
            items: components["schemas"]["MemoryOut"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** MemoryProposal */
        MemoryProposal: {
            /**
             * Proposal Id
             * Format: uuid
             */
            proposal_id: string;
            /** Query */
            query: string;
            /** Answer */
            answer: string;
            /** Sources */
            sources?: string[];
            /**
             * Confidence
             * @default 0
             */
            confidence: number;
            /**
             * Status
             * @default pending
             * @enum {string}
             */
            status: "pending" | "approved" | "rejected";
            /** Rejected Reason */
            rejected_reason?: string | null;
            /** Memory Id */
            memory_id?: string | null;
            /** Trace Id */
            trace_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Resolved At */
            resolved_at?: string | null;
        };
        /** MemoryProposalPage */
        MemoryProposalPage: {
            /** Items */
            items: components["schemas"]["MemoryProposal"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** MessageOut */
        MessageOut: {
            /**
             * Message Id
             * Format: uuid
             */
            message_id: string;
            /** Role */
            role: string;
            /** Content */
            content: string;
            /** Plan Id */
            plan_id: string | null;
            /** Evidence */
            evidence: components["schemas"]["EvidenceRef"][];
            /** Confidence */
            confidence: number | null;
            /** Degraded */
            degraded: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** NodeWithNeighborhood */
        NodeWithNeighborhood: {
            node: components["schemas"]["GraphNode"];
            /** Neighbors */
            neighbors: components["schemas"]["GraphNeighbor"][];
        };
        /** NoteIn */
        NoteIn: {
            /**
             * Template
             * @example MaquinaHTB
             */
            template: string;
            /**
             * Folder
             * @example Security/HackTheBox/Máquinas
             */
            folder: string;
            /**
             * Title
             * @example Fawn
             */
            title: string;
        };
        /** NoteOut */
        NoteOut: {
            /** Path */
            path: string;
        };
        /** PatchMemoryProposalRequest */
        PatchMemoryProposalRequest: {
            /**
             * Status
             * @enum {string}
             */
            status: "approved" | "rejected";
            /** Reason */
            reason?: string | null;
        };
        /** PatchNodeRequest */
        PatchNodeRequest: {
            /** Canonical Name */
            canonical_name?: string | null;
            /** Node Type */
            node_type?: string | null;
            /** Aliases */
            aliases?: string[] | null;
        };
        /** PatchRecommendationRequest */
        PatchRecommendationRequest: {
            /**
             * Status
             * @enum {string}
             */
            status: "accepted" | "dismissed";
            /** Reason */
            reason?: string | null;
        };
        /** PatchRelationRequest */
        PatchRelationRequest: {
            /** Relation Type */
            relation_type?: string | null;
            /** Confidence */
            confidence?: number | null;
        };
        /** PeriodSummary */
        PeriodSummary: {
            /** Total Plans */
            total_plans: number;
            /** Degraded Plans */
            degraded_plans: number;
            /** Degradation Rate */
            degradation_rate: number;
            /** Avg Latency Ms */
            avg_latency_ms: number;
            /** Total Tokens */
            total_tokens: number;
        };
        /** PlanMetricsOut */
        PlanMetricsOut: {
            /**
             * Since
             * Format: date-time
             */
            since: string;
            current_period: components["schemas"]["PeriodSummary"];
            previous_period: components["schemas"]["PeriodSummary"] | null;
            /** Latency */
            latency: components["schemas"]["LatencyBucket"][];
            /** Degradation By Reason */
            degradation_by_reason: components["schemas"]["DegradationBreakdown"][];
            /** Agent Distribution */
            agent_distribution: components["schemas"]["AgentDistribution"][];
            /** Agent Latency */
            agent_latency: components["schemas"]["AgentLatency"][];
            /** Insights */
            insights: components["schemas"]["Insight"][];
        };
        /** PlanOut */
        PlanOut: {
            /**
             * Plan Id
             * Format: uuid
             */
            plan_id: string;
            /** Query */
            query: string;
            /** Steps */
            steps: components["schemas"]["PlanStep"][];
            /** Post */
            post: components["schemas"]["PlanStep"][];
            /** Degraded */
            degraded: boolean;
            /** Degraded Reason */
            degraded_reason: string | null;
            /** Elapsed Ms */
            elapsed_ms: number;
            /** Trace Id */
            trace_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** PlanPage */
        PlanPage: {
            /** Items */
            items: components["schemas"]["PlanSummary"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /**
         * PlanStep
         * @description Un paso del plan; la unidad de traza y depuración (doc 03 §3). `inputs`
         *     es lo que el Planner le pasa al agente — antes no existía porque el
         *     pipeline fijo no necesitaba parametrizar nada por paso.
         */
        PlanStep: {
            /** Id */
            id: string;
            /** Agent */
            agent: string;
            /** Task */
            task: string;
            /** Inputs */
            inputs?: {
                [key: string]: unknown;
            };
            /** Depends On */
            depends_on?: string[];
            /** Evidence Count */
            evidence_count?: number | null;
            /** Confidence */
            confidence?: number | null;
            cost?: components["schemas"]["Cost"] | null;
        };
        /**
         * PlanSummary
         * @description Versión liviana de `PlanOut` para el listado — sin `steps`/`post`.
         */
        PlanSummary: {
            /**
             * Plan Id
             * Format: uuid
             */
            plan_id: string;
            /** Query */
            query: string;
            /** Degraded */
            degraded: boolean;
            /** Degraded Reason */
            degraded_reason: string | null;
            /** Elapsed Ms */
            elapsed_ms: number;
            /** Trace Id */
            trace_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** QueryRequest */
        QueryRequest: {
            /** Query */
            query: string;
            /**
             * Limit
             * @default 8
             */
            limit: number;
            /**
             * Mode
             * @default hybrid
             * @enum {string}
             */
            mode: "hybrid" | "lexical" | "vector";
            /** Conversation Id */
            conversation_id?: string | null;
        };
        /** QueryResponse */
        QueryResponse: {
            /** Query */
            query: string;
            /** Answer */
            answer: string;
            /** Evidence */
            evidence: components["schemas"]["EvidenceRef"][];
            /** Confidence */
            confidence: number;
            /** Plan */
            plan: components["schemas"]["PlanStep"][];
            /** Degraded */
            degraded: boolean;
            /** Trace Id */
            trace_id: string;
            /** Plan Id */
            plan_id: string;
            /** Conversation Id */
            conversation_id: string;
        };
        /** Recommendation */
        Recommendation: {
            /**
             * Recommendation Id
             * Format: uuid
             */
            recommendation_id: string;
            /**
             * Type
             * @enum {string}
             */
            type: "gap" | "contradiction" | "related_relation" | "roadmap" | "reorganization";
            /** Title */
            title: string;
            /**
             * Description
             * @default
             */
            description: string;
            /** Evidence */
            evidence?: components["schemas"]["EvidenceRef"][];
            /** Target Entities */
            target_entities?: string[];
            /**
             * Confidence
             * @default 0
             */
            confidence: number;
            /**
             * Priority
             * @default 0
             */
            priority: number;
            /**
             * Status
             * @default pending
             * @enum {string}
             */
            status: "pending" | "accepted" | "dismissed" | "expired" | "superseded";
            /** Dismissed Reason */
            dismissed_reason?: string | null;
            /** Source Event Id */
            source_event_id?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Resolved At */
            resolved_at?: string | null;
        };
        /** RecommendationPage */
        RecommendationPage: {
            /** Items */
            items: components["schemas"]["Recommendation"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /**
         * SearchHitOut
         * @description Cada hit incluye la evidencia mínima {doc_id, chunk_id, quote} (doc 06 §2).
         */
        SearchHitOut: {
            /**
             * Doc Id
             * Format: uuid
             */
            doc_id: string;
            /**
             * Chunk Id
             * Format: uuid
             */
            chunk_id: string;
            /** Quote */
            quote: string;
            /** Score */
            score: number;
            /** Source */
            source: string;
            /** Title */
            title: string | null;
            /** Connector */
            connector: string | null;
            /** Source Id */
            source_id: string | null;
            /** Heading */
            heading: string | null;
        };
        /** SearchRequest */
        SearchRequest: {
            /** Query */
            query: string;
            /**
             * Limit
             * @default 10
             */
            limit: number;
            /**
             * Mode
             * @default hybrid
             * @enum {string}
             */
            mode: "hybrid" | "lexical" | "vector";
        };
        /** SearchResponse */
        SearchResponse: {
            /** Query */
            query: string;
            /**
             * Mode
             * @enum {string}
             */
            mode: "hybrid" | "lexical" | "vector";
            /**
             * Degraded
             * @default false
             */
            degraded: boolean;
            /** Hits */
            hits: components["schemas"]["SearchHitOut"][];
        };
        /** ServiceStatus */
        ServiceStatus: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "error";
            /** Latency Ms */
            latency_ms: number;
            /** Detail */
            detail?: string | null;
        };
        /** SourceIn */
        SourceIn: {
            /** Name */
            name: string;
            /**
             * Connector
             * @example obsidian
             */
            connector: string;
            /** Config */
            config?: {
                [key: string]: unknown;
            };
        };
        /** SourceOut */
        SourceOut: {
            /** Name */
            name: string;
            /**
             * Connector
             * @example obsidian
             */
            connector: string;
            /** Config */
            config?: {
                [key: string]: unknown;
            };
            /**
             * Source Uuid
             * Format: uuid
             */
            source_uuid: string;
            /** Enabled */
            enabled: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * SourceRef
         * @description Fuente de una memoria con su confidence individual (doc 04 §5, decidido
         *     2026-08-13): habilita recalcular `confidence` al perder una fuente, igual
         *     que `source_confidences[]` en el grafo — acá cabe como objeto porque
         *     Postgres/JSONB sí admite listas de objetos (Neo4j no).
         */
        SourceRef: {
            /** Doc Id */
            doc_id: string;
            /** Confidence */
            confidence: number;
        };
        /** SyncAccepted */
        SyncAccepted: {
            /** Job Id */
            job_id: string;
            /**
             * Source Uuid
             * Format: uuid
             */
            source_uuid: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_sources_v1_sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceOut"][];
                };
            };
        };
    };
    create_source_v1_sources_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourceIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_source_v1_sources__source_uuid__sync_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_note_v1_notes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NoteIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoteOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_documents_v1_documents_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_v1_documents__doc_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_chunks_v1_documents__doc_id__chunks_get: {
        parameters: {
            query?: {
                cursor?: number | null;
                limit?: number;
            };
            header?: never;
            path: {
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChunkPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_v1_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    query_v1_query_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_node_v1_graph_nodes__node_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                node_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeWithNeighborhood"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_node_v1_graph_nodes__node_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                node_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchNodeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphNode"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_path_v1_graph_path_get: {
        parameters: {
            query: {
                from_id: string;
                to_id: string;
                max_hops?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphPathOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    query_v1_graph_query_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GraphQueryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphQueryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_relation_v1_graph_relations__relation_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                relation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_relation_v1_graph_relations__relation_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                relation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchRelationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphRelation"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_memories_v1_memory_get: {
        parameters: {
            query?: {
                type?: ("episodic" | "semantic" | "procedural" | "temporal" | "preference") | null;
                q?: string | null;
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_memory_v1_memory__memory_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                memory_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_plans_v1_plans_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
                degraded_only?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_plan_metrics_v1_plans_metrics_get: {
        parameters: {
            query?: {
                since_hours?: number;
                bucket?: "hour" | "day";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanMetricsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_plan_v1_plans__plan_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_conversations_v1_conversations_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_conversation_v1_conversations__conversation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_conversation_v1_conversations__conversation_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_recommendations_v1_recommendations_get: {
        parameters: {
            query?: {
                type?: ("gap" | "contradiction" | "related_relation" | "roadmap" | "reorganization") | null;
                status?: ("pending" | "accepted" | "dismissed" | "expired" | "superseded") | null;
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_recommendation_v1_recommendations__recommendation_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recommendation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchRecommendationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Recommendation"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_proposals_v1_memory_proposals_get: {
        parameters: {
            query?: {
                status?: ("pending" | "approved" | "rejected") | null;
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryProposalPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_proposal_v1_memory_proposals__proposal_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                proposal_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchMemoryProposalRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryProposal"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
