/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Verifica todos los servicios en paralelo; responde 200 siempre.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sources */
        get: operations["list_sources_v1_sources_get"];
        put?: never;
        /** Create Source */
        post: operations["create_source_v1_sources_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sources/{source_uuid}/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sync Source */
        post: operations["sync_source_v1_sources__source_uuid__sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Note */
        post: operations["create_note_v1_notes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Documents */
        get: operations["list_documents_v1_documents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/documents/{doc_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Document */
        get: operations["get_document_v1_documents__doc_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/documents/{doc_id}/chunks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Chunks */
        get: operations["list_chunks_v1_documents__doc_id__chunks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Search */
        post: operations["search_v1_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Query */
        post: operations["query_v1_query_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/graph/nodes/{node_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Node */
        get: operations["get_node_v1_graph_nodes__node_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Node */
        patch: operations["patch_node_v1_graph_nodes__node_id__patch"];
        trace?: never;
    };
    "/v1/graph/path": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Path */
        get: operations["get_path_v1_graph_path_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/graph/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Query */
        post: operations["query_v1_graph_query_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/graph/relations/{relation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Relation */
        delete: operations["delete_relation_v1_graph_relations__relation_id__delete"];
        options?: never;
        head?: never;
        /** Patch Relation */
        patch: operations["patch_relation_v1_graph_relations__relation_id__patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ChunkOut */
        ChunkOut: {
            /**
             * Chunk Id
             * Format: uuid
             */
            chunk_id: string;
            /**
             * Doc Id
             * Format: uuid
             */
            doc_id: string;
            /** Text */
            text: string;
            /** Position */
            position: number;
            /** Start Offset */
            start_offset: number | null;
            /** End Offset */
            end_offset: number | null;
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
            /** Has Embedding */
            has_embedding: boolean;
        };
        /** ChunkPage */
        ChunkPage: {
            /** Items */
            items: components["schemas"]["ChunkOut"][];
            /** Next Cursor */
            next_cursor: number | null;
        };
        /** DocumentDetail */
        DocumentDetail: {
            /**
             * Doc Id
             * Format: uuid
             */
            doc_id: string;
            /** Source Uuid */
            source_uuid: string | null;
            /** Connector */
            connector: string;
            /** Source Id */
            source_id: string;
            /** Title */
            title: string | null;
            /** Summary */
            summary: string | null;
            /** Author */
            author: string | null;
            /** Language */
            language: string | null;
            /** Keywords */
            keywords: string[];
            /** Links */
            links: string[];
            /** Confidence */
            confidence: number;
            /** Content Hash */
            content_hash: string | null;
            /** Created At */
            created_at: string | null;
            /** Modified At */
            modified_at: string | null;
            /**
             * Fetched At
             * Format: date-time
             */
            fetched_at: string;
            /** Source Metadata */
            source_metadata: {
                [key: string]: unknown;
            };
        };
        /** DocumentPage */
        DocumentPage: {
            /** Items */
            items: components["schemas"]["DocumentSummary"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** DocumentSummary */
        DocumentSummary: {
            /**
             * Doc Id
             * Format: uuid
             */
            doc_id: string;
            /** Source Uuid */
            source_uuid: string | null;
            /** Connector */
            connector: string;
            /** Source Id */
            source_id: string;
            /** Title */
            title: string | null;
            /** Summary */
            summary: string | null;
            /** Author */
            author: string | null;
            /** Language */
            language: string | null;
            /** Keywords */
            keywords: string[];
            /** Links */
            links: string[];
            /** Confidence */
            confidence: number;
            /** Content Hash */
            content_hash: string | null;
            /** Created At */
            created_at: string | null;
            /** Modified At */
            modified_at: string | null;
            /**
             * Fetched At
             * Format: date-time
             */
            fetched_at: string;
        };
        /**
         * EvidenceRef
         * @description Referencia citable. La evidencia mínima es {doc_id, chunk_id, quote};
         *     node_id/memory_id se rellenan en fases posteriores (grafo, memoria).
         */
        EvidenceRef: {
            /** Doc Id */
            doc_id?: string | null;
            /** Chunk Id */
            chunk_id?: string | null;
            /** Node Id */
            node_id?: string | null;
            /** Memory Id */
            memory_id?: string | null;
            /** Quote */
            quote?: string | null;
            /** Title */
            title?: string | null;
            /** Source Id */
            source_id?: string | null;
            /** Connector */
            connector?: string | null;
            /** Score */
            score?: number | null;
            /** Doc Type */
            doc_type?: string | null;
        };
        /** GraphNeighbor */
        GraphNeighbor: {
            relation: components["schemas"]["GraphRelation"];
            node: components["schemas"]["GraphNode"];
            /**
             * Direction
             * @enum {string}
             */
            direction: "outgoing" | "incoming";
        };
        /** GraphNode */
        GraphNode: {
            /** Id */
            id: string;
            /**
             * Node Type
             * @enum {string}
             */
            node_type: "Person" | "Project" | "Technology" | "Concept" | "Document" | "Task" | "Organization" | "Event" | "Skill";
            /** Canonical Name */
            canonical_name: string;
            /** Name */
            name: string;
            /** Aliases */
            aliases?: string[];
            /** Confidence */
            confidence: number;
            /** Sources */
            sources?: string[];
            /** Extracted By */
            extracted_by: string;
            /**
             * Locked
             * @default false
             */
            locked: boolean;
            /** Created At */
            created_at?: string | null;
            /** Updated At */
            updated_at?: string | null;
        };
        /** GraphPathOut */
        GraphPathOut: {
            /** Nodes */
            nodes: components["schemas"]["GraphNode"][];
            /** Relations */
            relations: components["schemas"]["GraphRelation"][];
        };
        /** GraphQueryRequest */
        GraphQueryRequest: {
            /**
             * Template
             * @enum {string}
             */
            template: "nodes_by_type" | "neighbors_by_type" | "most_connected";
            /** Node Type */
            node_type?: string | null;
            /** Node Id */
            node_id?: string | null;
            /** Cursor */
            cursor?: string | null;
            /**
             * Limit
             * @default 20
             */
            limit: number;
        };
        /** GraphQueryResponse */
        GraphQueryResponse: {
            /**
             * Template
             * @enum {string}
             */
            template: "nodes_by_type" | "neighbors_by_type" | "most_connected";
            /** Nodes */
            nodes?: components["schemas"]["GraphNode"][] | null;
            /** Neighbors */
            neighbors?: components["schemas"]["GraphNeighbor"][] | null;
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** GraphRelation */
        GraphRelation: {
            /** Id */
            id: string;
            /**
             * Relation Type
             * @enum {string}
             */
            relation_type: "USES" | "RELATED_TO" | "AUTHORED_BY" | "PART_OF" | "DEPENDS_ON" | "PREREQUISITE_OF" | "MENTIONS" | "KNOWS" | "CONTRADICTS" | "SUPERSEDES";
            /** Source Id */
            source_id: string;
            /** Target Id */
            target_id: string;
            /** Confidence */
            confidence: number;
            /** Sources */
            sources?: string[];
            /** Extracted By */
            extracted_by: string;
            /** Extracted At */
            extracted_at?: string | null;
            /**
             * Rejected
             * @default false
             */
            rejected: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /** Services */
            services: {
                [key: string]: components["schemas"]["ServiceStatus"];
            };
        };
        /** NodeWithNeighborhood */
        NodeWithNeighborhood: {
            node: components["schemas"]["GraphNode"];
            /** Neighbors */
            neighbors: components["schemas"]["GraphNeighbor"][];
        };
        /** NoteIn */
        NoteIn: {
            /**
             * Template
             * @example MaquinaHTB
             */
            template: string;
            /**
             * Folder
             * @example Security/HackTheBox/Máquinas
             */
            folder: string;
            /**
             * Title
             * @example Fawn
             */
            title: string;
        };
        /** NoteOut */
        NoteOut: {
            /** Path */
            path: string;
        };
        /** PatchNodeRequest */
        PatchNodeRequest: {
            /** Canonical Name */
            canonical_name?: string | null;
            /** Node Type */
            node_type?: string | null;
            /** Aliases */
            aliases?: string[] | null;
        };
        /** PatchRelationRequest */
        PatchRelationRequest: {
            /** Relation Type */
            relation_type?: string | null;
            /** Confidence */
            confidence?: number | null;
        };
        /**
         * PlanStep
         * @description Un paso del plan (fijo en Fase 1); la unidad de traza y depuración (doc 03 §3).
         */
        PlanStep: {
            /** Id */
            id: string;
            /** Agent */
            agent: string;
            /** Task */
            task: string;
            /** Depends On */
            depends_on?: string[];
            /** Evidence Count */
            evidence_count?: number | null;
        };
        /** QueryRequest */
        QueryRequest: {
            /** Query */
            query: string;
            /**
             * Limit
             * @default 8
             */
            limit: number;
            /**
             * Mode
             * @default hybrid
             * @enum {string}
             */
            mode: "hybrid" | "lexical" | "vector";
        };
        /** QueryResponse */
        QueryResponse: {
            /** Query */
            query: string;
            /** Answer */
            answer: string;
            /** Evidence */
            evidence: components["schemas"]["EvidenceRef"][];
            /** Confidence */
            confidence: number;
            /** Plan */
            plan: components["schemas"]["PlanStep"][];
            /** Degraded */
            degraded: boolean;
            /** Trace Id */
            trace_id: string;
        };
        /**
         * SearchHitOut
         * @description Cada hit incluye la evidencia mínima {doc_id, chunk_id, quote} (doc 06 §2).
         */
        SearchHitOut: {
            /**
             * Doc Id
             * Format: uuid
             */
            doc_id: string;
            /**
             * Chunk Id
             * Format: uuid
             */
            chunk_id: string;
            /** Quote */
            quote: string;
            /** Score */
            score: number;
            /** Source */
            source: string;
            /** Title */
            title: string | null;
            /** Connector */
            connector: string | null;
            /** Source Id */
            source_id: string | null;
            /** Heading */
            heading: string | null;
        };
        /** SearchRequest */
        SearchRequest: {
            /** Query */
            query: string;
            /**
             * Limit
             * @default 10
             */
            limit: number;
            /**
             * Mode
             * @default hybrid
             * @enum {string}
             */
            mode: "hybrid" | "lexical" | "vector";
        };
        /** SearchResponse */
        SearchResponse: {
            /** Query */
            query: string;
            /**
             * Mode
             * @enum {string}
             */
            mode: "hybrid" | "lexical" | "vector";
            /**
             * Degraded
             * @default false
             */
            degraded: boolean;
            /** Hits */
            hits: components["schemas"]["SearchHitOut"][];
        };
        /** ServiceStatus */
        ServiceStatus: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "error";
            /** Latency Ms */
            latency_ms: number;
            /** Detail */
            detail?: string | null;
        };
        /** SourceIn */
        SourceIn: {
            /** Name */
            name: string;
            /**
             * Connector
             * @example obsidian
             */
            connector: string;
            /** Config */
            config?: {
                [key: string]: unknown;
            };
        };
        /** SourceOut */
        SourceOut: {
            /** Name */
            name: string;
            /**
             * Connector
             * @example obsidian
             */
            connector: string;
            /** Config */
            config?: {
                [key: string]: unknown;
            };
            /**
             * Source Uuid
             * Format: uuid
             */
            source_uuid: string;
            /** Enabled */
            enabled: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** SyncAccepted */
        SyncAccepted: {
            /** Job Id */
            job_id: string;
            /**
             * Source Uuid
             * Format: uuid
             */
            source_uuid: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_sources_v1_sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceOut"][];
                };
            };
        };
    };
    create_source_v1_sources_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourceIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_source_v1_sources__source_uuid__sync_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_note_v1_notes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NoteIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoteOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_documents_v1_documents_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_v1_documents__doc_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_chunks_v1_documents__doc_id__chunks_get: {
        parameters: {
            query?: {
                cursor?: number | null;
                limit?: number;
            };
            header?: never;
            path: {
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChunkPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_v1_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    query_v1_query_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_node_v1_graph_nodes__node_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                node_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeWithNeighborhood"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_node_v1_graph_nodes__node_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                node_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchNodeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphNode"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_path_v1_graph_path_get: {
        parameters: {
            query: {
                from_id: string;
                to_id: string;
                max_hops?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphPathOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    query_v1_graph_query_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GraphQueryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphQueryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_relation_v1_graph_relations__relation_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                relation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_relation_v1_graph_relations__relation_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                relation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchRelationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphRelation"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
