/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Verifica todos los servicios en paralelo; responde 200 siempre.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sources */
        get: operations["list_sources_v1_sources_get"];
        put?: never;
        /** Create Source */
        post: operations["create_source_v1_sources_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sources/{source_uuid}/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sync Source */
        post: operations["sync_source_v1_sources__source_uuid__sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Documents */
        get: operations["list_documents_v1_documents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/documents/{doc_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Document */
        get: operations["get_document_v1_documents__doc_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/documents/{doc_id}/chunks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Chunks */
        get: operations["list_chunks_v1_documents__doc_id__chunks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Search */
        post: operations["search_v1_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Query */
        post: operations["query_v1_query_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ChunkOut */
        ChunkOut: {
            /**
             * Chunk Id
             * Format: uuid
             */
            chunk_id: string;
            /**
             * Doc Id
             * Format: uuid
             */
            doc_id: string;
            /** Text */
            text: string;
            /** Position */
            position: number;
            /** Start Offset */
            start_offset: number | null;
            /** End Offset */
            end_offset: number | null;
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
            /** Has Embedding */
            has_embedding: boolean;
        };
        /** ChunkPage */
        ChunkPage: {
            /** Items */
            items: components["schemas"]["ChunkOut"][];
            /** Next Cursor */
            next_cursor: number | null;
        };
        /** DocumentDetail */
        DocumentDetail: {
            /**
             * Doc Id
             * Format: uuid
             */
            doc_id: string;
            /** Source Uuid */
            source_uuid: string | null;
            /** Connector */
            connector: string;
            /** Source Id */
            source_id: string;
            /** Title */
            title: string | null;
            /** Summary */
            summary: string | null;
            /** Author */
            author: string | null;
            /** Language */
            language: string | null;
            /** Keywords */
            keywords: string[];
            /** Links */
            links: string[];
            /** Confidence */
            confidence: number;
            /** Content Hash */
            content_hash: string | null;
            /** Created At */
            created_at: string | null;
            /** Modified At */
            modified_at: string | null;
            /**
             * Fetched At
             * Format: date-time
             */
            fetched_at: string;
            /** Source Metadata */
            source_metadata: {
                [key: string]: unknown;
            };
        };
        /** DocumentPage */
        DocumentPage: {
            /** Items */
            items: components["schemas"]["DocumentSummary"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** DocumentSummary */
        DocumentSummary: {
            /**
             * Doc Id
             * Format: uuid
             */
            doc_id: string;
            /** Source Uuid */
            source_uuid: string | null;
            /** Connector */
            connector: string;
            /** Source Id */
            source_id: string;
            /** Title */
            title: string | null;
            /** Summary */
            summary: string | null;
            /** Author */
            author: string | null;
            /** Language */
            language: string | null;
            /** Keywords */
            keywords: string[];
            /** Links */
            links: string[];
            /** Confidence */
            confidence: number;
            /** Content Hash */
            content_hash: string | null;
            /** Created At */
            created_at: string | null;
            /** Modified At */
            modified_at: string | null;
            /**
             * Fetched At
             * Format: date-time
             */
            fetched_at: string;
        };
        /**
         * EvidenceRef
         * @description Referencia citable. La evidencia mínima es {doc_id, chunk_id, quote};
         *     node_id/memory_id se rellenan en fases posteriores (grafo, memoria).
         */
        EvidenceRef: {
            /** Doc Id */
            doc_id?: string | null;
            /** Chunk Id */
            chunk_id?: string | null;
            /** Node Id */
            node_id?: string | null;
            /** Memory Id */
            memory_id?: string | null;
            /** Quote */
            quote?: string | null;
            /** Title */
            title?: string | null;
            /** Source Id */
            source_id?: string | null;
            /** Connector */
            connector?: string | null;
            /** Score */
            score?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /** Services */
            services: {
                [key: string]: components["schemas"]["ServiceStatus"];
            };
        };
        /**
         * PlanStep
         * @description Un paso del plan (fijo en Fase 1); la unidad de traza y depuración (doc 03 §3).
         */
        PlanStep: {
            /** Id */
            id: string;
            /** Agent */
            agent: string;
            /** Task */
            task: string;
            /** Depends On */
            depends_on?: string[];
            /** Evidence Count */
            evidence_count?: number | null;
        };
        /** QueryRequest */
        QueryRequest: {
            /** Query */
            query: string;
            /**
             * Limit
             * @default 8
             */
            limit: number;
            /**
             * Mode
             * @default hybrid
             * @enum {string}
             */
            mode: "hybrid" | "lexical" | "vector";
        };
        /** QueryResponse */
        QueryResponse: {
            /** Query */
            query: string;
            /** Answer */
            answer: string;
            /** Evidence */
            evidence: components["schemas"]["EvidenceRef"][];
            /** Confidence */
            confidence: number;
            /** Plan */
            plan: components["schemas"]["PlanStep"][];
            /** Degraded */
            degraded: boolean;
            /** Trace Id */
            trace_id: string;
        };
        /**
         * SearchHitOut
         * @description Cada hit incluye la evidencia mínima {doc_id, chunk_id, quote} (doc 06 §2).
         */
        SearchHitOut: {
            /**
             * Doc Id
             * Format: uuid
             */
            doc_id: string;
            /**
             * Chunk Id
             * Format: uuid
             */
            chunk_id: string;
            /** Quote */
            quote: string;
            /** Score */
            score: number;
            /** Source */
            source: string;
            /** Title */
            title: string | null;
            /** Connector */
            connector: string | null;
            /** Source Id */
            source_id: string | null;
            /** Heading */
            heading: string | null;
        };
        /** SearchRequest */
        SearchRequest: {
            /** Query */
            query: string;
            /**
             * Limit
             * @default 10
             */
            limit: number;
            /**
             * Mode
             * @default hybrid
             * @enum {string}
             */
            mode: "hybrid" | "lexical" | "vector";
        };
        /** SearchResponse */
        SearchResponse: {
            /** Query */
            query: string;
            /**
             * Mode
             * @enum {string}
             */
            mode: "hybrid" | "lexical" | "vector";
            /**
             * Degraded
             * @default false
             */
            degraded: boolean;
            /** Hits */
            hits: components["schemas"]["SearchHitOut"][];
        };
        /** ServiceStatus */
        ServiceStatus: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "error";
            /** Latency Ms */
            latency_ms: number;
            /** Detail */
            detail?: string | null;
        };
        /** SourceIn */
        SourceIn: {
            /** Name */
            name: string;
            /**
             * Connector
             * @example obsidian
             */
            connector: string;
            /** Config */
            config?: {
                [key: string]: unknown;
            };
        };
        /** SourceOut */
        SourceOut: {
            /** Name */
            name: string;
            /**
             * Connector
             * @example obsidian
             */
            connector: string;
            /** Config */
            config?: {
                [key: string]: unknown;
            };
            /**
             * Source Uuid
             * Format: uuid
             */
            source_uuid: string;
            /** Enabled */
            enabled: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** SyncAccepted */
        SyncAccepted: {
            /** Job Id */
            job_id: string;
            /**
             * Source Uuid
             * Format: uuid
             */
            source_uuid: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_sources_v1_sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceOut"][];
                };
            };
        };
    };
    create_source_v1_sources_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourceIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_source_v1_sources__source_uuid__sync_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_documents_v1_documents_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_v1_documents__doc_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_chunks_v1_documents__doc_id__chunks_get: {
        parameters: {
            query?: {
                cursor?: number | null;
                limit?: number;
            };
            header?: never;
            path: {
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChunkPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_v1_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    query_v1_query_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
